-- Script to create company table

CREATE TABLE COMPANY ( 	ID              INT         NOT NULL PRIMARY KEY AUTO_INCREMENT, 
			NAME            VARCHAR(64) NOT NULL,
			ADDRESS_STR1    VARCHAR(32),
			ADDRESS_STR2    VARCHAR(32),
			ADDRESS_CITY    VARCHAR(32),
			ADDRESS_ZIP     VARCHAR(12),
			ADDRESS_STATE   VARCHAR(32),
			ADDRESS_COUNTRY VARCHAR(32)
		     );

ALTER TABLE COMPANY AUTO_INCREMENT=1000;
